name: "Deploy"

on:
  workflow_call:
    inputs:
      application:
        required: true
        type: string
      overwrite:
        required: false
        default: false
        type: boolean
  workflow_dispatch:
    inputs:
     application:
      description: "Environment to run against"
      required: true
      type: string
    overwrite:
      description: "Overwrite remote environment"
      required: false
      default: false
      type: boolean

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          git_push_flags: ${{ inputs.overwrite == true && '--force' || ''}}
          git_remote_url: 'ssh://dokku@abenteuerleben-ev.de:22/${{ inputs.application }}'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
