name: "Deploying"

on:
  push:
    branches: [ 'master' ]
  workflow_dispatch:
    inputs:
     environment:
      description: "environment to run against"
      type: string
      required: true

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    needs: test
    if: ${{ github.event == 'push' || github.event == 'workflow_dispatch' && inputs.environment == 'production' }} 
    steps:
      - name: Print something 
        run: echo 'hi :)'

  deploy-production:
    runs-on: ubuntu-latest
    needs: test
    if: ${{ github.event == 'push' || github.event == 'workflow_dispatch' && inputs.environment == 'production' }} 
    steps:
      - name: Cloning repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: 'ssh://dokku@abenteuerleben-ev.de:22/aleben'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
