name: "Deploy"

on:
  workflow_call:
    inputs:
      application:
        required: true
        type: string
  workflow_dispatch:
    inputs:
     application:
      description: "environment to run against"
      required: true
      type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cloning repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: 'ssh://dokku@abenteuerleben-ev.de:22/${{ inputs.application }}'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
