name: Merge to Master 

on:
  workflow_dispatch:
  push:
    branch:
      - master

jobs:
  test:
    uses: anosim114/abenteuerleben-rails/.github/workflows/test.yml

  deploy-staging:
    uses: anosim114/abenteuerleben-rails/.github/workflows/deploy.yml
    needs: test
    with:
      application: bleben

  deploy-production:
    uses: anosim114/abenteuerleben-rails/.github/workflows/deploy.yml
    needs: deploy-staging
    with:
      application: aleben