name: Merge to Master

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'

jobs:
  test:
    uses: anosim114/abenteuerleben-rails/.github/workflows/tests_general.yml@master
  e2e:
    uses: anosim114/abenteuerleben-rails/.github/workflows/tests_system.yml@master

  deploy-staging:
    uses: anosim114/abenteuerleben-rails/.github/workflows/deploy.yml@master
    needs:
      - test
      - e2e
    with:
      application: bleben
      overwrite: true
    secrets: inherit

  deploy-production:
    uses: anosim114/abenteuerleben-rails/.github/workflows/deploy.yml@master
    needs: deploy-staging
    with:
      application: aleben
    secrets: inherit
