name: Merge to Master

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'

jobs:
  test:
    uses: FECG-Blomberg/abenteuerleben/.github/workflows/tests.yml@master

  deploy-staging:
    uses: FECG-Blomberg/abenteuerleben/.github/workflows/deploy.yml@master
    needs:
      - test
    with:
      application: bleben
      overwrite: true
    secrets: inherit

  production-delay:
    runs-on: ubuntu-latest
    needs: deploy-staging
    steps:
      - name: Delay deploy to production for cancelling possibility
        run: sleep 5m

  deploy-production:
    uses: FECG-Blomberg/abenteuerleben/.github/workflows/deploy.yml@master
    needs: production-delay
    with:
      application: aleben
    secrets: inherit
