name: Merge to Master 

on:
  workflow_dispatch:
  push:
    branches:
      - 'master'

jobs:
  test:
    uses: anosim114/abenteuerleben-rails/.github/workflows/test.yml@master

  deploy-staging:
    uses: anosim114/abenteuerleben-rails/.github/workflows/deploy.yml@master
    needs: test
    with:
      application: bleben
    secrets: inherit

  # deploy-production:
  #   uses: anosim114/abenteuerleben-rails/.github/workflows/deploy.yml@master
  #   needs: deploy-staging
  #   with:
  #     application: aleben
  #   secrets: inherit
