# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: "Feature Branch Push"
on:
  workflow_dispatch:
  push:
    branches-ignore:
      - master

jobs:
  test:
    uses: FECG-Blomberg/abenteuerleben/.github/workflows/tests.yml@change-preferred-camp-to-switch
